name: AppSecNub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  security-scan:
    name: SAST and Dependencies
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    defaults:
      run:
        working-directory: app
    env:
      DC_DATA_DIR: ${{ github.workspace }}/.dc-data

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Semgrep
        run: pip install semgrep

      - name : Tool version
        run: semgrep --version

      - name: Run Semgrep
        run: |
          mkdir -p ../out
          semgrep --config auto --json > ../out/semgrep-report.json
      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
         name: semgrep-report
         path: out/semgrep-report.json

      - name: Cache Dependency-Check Data
        uses: actions/cache@v4
        with:
          path: ${{ env.DC_DATA_DIR }}
          key: ${{ runner.os }}-dcdata-${{ env.DC_VERSION }}
          restore-keys: |
            ${{ runner.os }}-dcdata-

      - name: Instalar Dependency-Check
        run: |
          apt-get update && apt-get install -y openjdk-17-jre-headless wget unzip
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.3/dependency-check-12.1.3-release.zip
          unzip dependency-check-12.1.3-release.zip -d ../tools
      
      - name: Verificar Dependency-Check Version
        run: |
          ../tools/dependency-check/bin/dependency-check.sh --version

      - name: Rodar Dependency-Check
        continue-on-error: true
        run: |
          mkdir -p ../out
          ../tools/dependency-check/bin/dependency-check.sh \
            --project "app" \
            --scan . \
            --format "JSON" \
            --data "${DC_DATA_DIR}" \
            --nvdApiKey "47a91695-56d0-4ec1-b6e5-b81dd7d9f0e9" \
            --disableArchive \
            --failOnCVSS 0 \
            --out ../out

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: dc-security-reports
          path: out/
