name: AppSecNub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  security-scan:
    name: SAST and Dependencies
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: |
          mkdir -p ../out
          semgrep --config auto --json > ../out/semgrep-report.json

      - name: Print findings
        run: cat ../out/semgrep-report.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: out/semgrep-report.json