name: AppSecNub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  security-scan:
    name: SAST and Dependencies
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    defaults:
      run:
        working-directory: .

    steps:
      - name: Instalar Dependency-Check
        run: |
          apt-get update && apt-get install -y openjdk-17-jre-headless wget unzip
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.3/dependency-check-12.1.3-release.zip
          unzip dependency-check-12.1.3-release.zip -d ../tools
      
      - name: Verificar Dependency-Check Version
        run: |
          ../tools/dependency-check/bin/dependency-check.sh --version

      - name : Purge DC Database
        continue-on-error: true
        run: ../tools/dependency-check/bin/dependency-check.sh --purge        

      - name: Rodar Dependency-Check
        continue-on-error: true
        run: |
          mkdir -p ../out
          ../tools/dependency-check/bin/dependency-check.sh \
            --project "app" \
            --scan . \
            --format "JSON" \
            --nvdApiKey "47a91695-56d0-4ec1-b6e5-b81dd7d9f0e9" \
            --disableArchive \
            --failOnCVSS 0 \
            --out ../out
